# Generated by Django 3.2.23 on 2023-12-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20231210_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
