# Generated by Django 3.2.23 on 2023-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_profile_image_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image_url',
        ),
    ]
