# Generated by Django 3.2.23 on 2023-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('review_text', models.TextField(max_length=500, null=True)),
                ('review_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews_images/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
