# Generated by Django 3.2.23 on 2023-12-05 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231205_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
