# Generated by Django 3.2.23 on 2023-12-05 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20231205_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
