# Generated by Django 3.2.23 on 2023-12-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_default_email'),
        ('reviews', '0005_auto_20231205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_profile', to='profiles.userprofile'),
        ),
    ]
