# Generated by Django 3.2.23 on 2023-12-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviews_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user_profile',
        ),
    ]
