# Generated by Django 3.2.23 on 2023-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_reviews_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
