# Generated by Django 3.2.23 on 2023-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=60)),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
