# Generated by Django 3.2.23 on 2023-11-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Special Offers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='additional_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.SET_NULL, to='products.specialoffers'),
            preserve_default='True',
        ),
    ]
