# Generated by Django 3.2.23 on 2023-12-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231207_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.specialoffers'),
        ),
    ]
