# Generated by Django 3.2.23 on 2023-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_special_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='b_stock',
        ),
    ]
