# Generated by Django 3.2.23 on 2023-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_b_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b_stock',
            field=models.BooleanField(default=False),
        ),
    ]
