# Generated by Django 3.2.23 on 2023-12-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_b_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='b_stock',
        ),
    ]
